[package]
name = "conduit-hyper"
version = "0.4.1"
authors = ["Justin Geibel <jtgeibel@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Host a conduit based web application on a hyper server"
repository = "https://github.com/jtgeibel/conduit-hyper"
readme = "README.md"
edition = "2018"
rust-version = "1.46.0"

[dependencies]
bytes = "1"
conduit = "0.10.0"
hyper = { version = "0.14", features = ["server", "http1", "stream", "tcp"] }
http = "0.2"
percent-encoding = "2"
thiserror = "1.0.31"
tracing = "0.1"
tokio = { version = "1", features = ["fs"] }
tokio-stream = "0.1"
tower-service = "0.3"

[dev-dependencies]
conduit-router = "0.10.0"
futures-util = "0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.7"
