name: CI

on:
  push:
  pull_request:

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-18.04
    strategy:
      # TODO: [ci] should be true if GitHub Actions supports ""allow failures" on matrix
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - nightly

    env:
      CARGO_INCREMENTAL: 0
      RUSTFLAGS: "-C debuginfo=0 -D warnings"

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true

      - name: Install ${{ matrix.rust }} Rust
        run: |
          if [[ ! -d "$HOME/.cargo" || ! -d "$HOME/.rustup" ]]; then
              curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
              sh rustup-init.sh -y --default-toolchain none
          fi
          rustup set profile minimal
          rustup update ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}

      - name: Install lint tools
        if: matrix.rust == 'stable'
        run: |
          rustup component add rustfmt
          rustup component add clippy

      - uses: Swatinem/rust-cache@v1.3.0

      - name: Lint
        if: matrix.rust == 'stable'
        run: |
          cargo fmt -- --check
          cargo clippy --all-targets --all-features --all

      - name: Test
        run: cargo test
